version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: cimg/node:10.24.1
      - image: mongo:4.2.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Use some memory
          command: |
            dd if=/dev/zero of=testfile bs=1M count=1500
            # sudo swapoff -a
            # sudo sysctl -w vm.max_map_count=100
            cat testfile > /dev/null &
            watch -n 1 free -m
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: test-results.xml
