version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: cimg/node:10.24.1
      - image: mongo:4.2.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Use some memory
          command: |
            # Create a file with a large size
            dd if=/dev/zero of=testfile bs=1M count=10000

            # Disable the swap space
            sudo swapoff -a

            # Limit the amount of memory available to the system
            sudo sysctl -w vm.max_map_count=100

            # Start a process that will consume a large amount of memory
            cat testfile > /dev/null &

            # Monitor the memory usage of the system
            watch -n 1 free -m

            # Wait for the memory usage to reach the limit set in step 3
            # You should see the system start to swap memory to disk, which will cause the system to slow down significantly.

            # Stop the process
            # killall cat
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: test-results.xml
